# Generated by Django 3.1.5 on 2021-01-16 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseOrderIetms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.baseorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.baseproduct')),
            ],
        ),
    ]
